# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/ROM_32bit_11952_1/ROM_32bit_11952.xci
# IP: The module: 'ROM_32bit_11952' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/ROM_32bit_11952_1/ROM_32bit_11952_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_32bit_11952'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/ROM_32bit_11952_1/ROM_32bit_11952.xci
# IP: The module: 'ROM_32bit_11952' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/ROM_32bit_11952_1/ROM_32bit_11952_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_32bit_11952'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
