# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/con_pin.xdc

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/Resizer/mult_8_8_16/mult_8_8_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_8_8_16 || ORIG_REF_NAME==mult_8_8_16} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/subtracter_16bit/subtracter_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==subtracter_16bit || ORIG_REF_NAME==subtracter_16bit} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/RAM_15bit_32_1/RAM_15bit_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_15bit_32 || ORIG_REF_NAME==RAM_15bit_32} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/RAM_16bit_16_1/RAM_16bit_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_16bit_16 || ORIG_REF_NAME==RAM_16bit_16} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/DDR/ip/MMCM/MMCM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MMCM || ORIG_REF_NAME==MMCM} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/Resizer/mult_16_8_24/mult_16_8_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_16_8_24 || ORIG_REF_NAME==mult_16_8_24} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/Resizer/ROM_8bit_260/ROM_8bit_260.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_8bit_260 || ORIG_REF_NAME==ROM_8bit_260} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/exp_1/exp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp || ORIG_REF_NAME==exp} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/DDR/ip/MIG/MIG.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIG || ORIG_REF_NAME==MIG} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/multi_16bit_1/multi_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_16bit || ORIG_REF_NAME==multi_16bit} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/ROM_16bit_1368_1/ROM_16bit_1368.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_16bit_1368 || ORIG_REF_NAME==ROM_16bit_1368} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/multi_0point2/multi_0point2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_0point2 || ORIG_REF_NAME==multi_0point2} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/DDR/ip/FIFO/FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO || ORIG_REF_NAME==FIFO} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/Resizer/UROM/UROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UROM || ORIG_REF_NAME==UROM} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/Resizer/VROM/VROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VROM || ORIG_REF_NAME==VROM} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/DDR/ip/AHB_to_AXI_1/AHB_to_AXI.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AHB_to_AXI || ORIG_REF_NAME==AHB_to_AXI} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/Resizer/ROM_9bit_260/ROM_9bit_260.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_9bit_260 || ORIG_REF_NAME==ROM_9bit_260} -quiet] -quiet
