comp_all: comp_img1 comp_img2 comp_img3 comp_img4 comp_img5 comp_img6 comp_img7

exec_all: 
	./img1 ./img2 ./img3 ./img4 ./img5 ./img6 ./img7

comp_img1:
	gcc img1_send.c -o img1

comp_img2:
	gcc img2_send.c -o img2

comp_img3:
	gcc img3_send.c -o img3

comp_img4:
	gcc img4_send.c -o img4

comp_img5:
	gcc img5_send.c -o img5

comp_img6:
	gcc img6_send.c -o img6

comp_img7:
	gcc img7_send.c -o img7