# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/ROM_16bit_1368_1/ROM_16bit_1368.xci
# IP: The module: 'ROM_16bit_1368' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/ROM_16bit_1368_1/ROM_16bit_1368_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_16bit_1368'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/ROM_16bit_1368_1/ROM_16bit_1368.xci
# IP: The module: 'ROM_16bit_1368' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/ROM_16bit_1368_1/ROM_16bit_1368_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_16bit_1368'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
