# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/RAM_81bit_32/RAM_81bit_32.xci
# IP: The module: 'RAM_81bit_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/RAM_81bit_32/RAM_81bit_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_81bit_32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/RAM_81bit_32/RAM_81bit_32.xci
# IP: The module: 'RAM_81bit_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl_camera/Peripherals/ACC/IP/RAM_81bit_32/RAM_81bit_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_81bit_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
