# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: G:/SoC/Projects/CortexM3_soc/Vivado/constrs/con_pin.xdc

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/Resizer/mult_8_8_16/mult_8_8_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_8_8_16 || ORIG_REF_NAME==mult_8_8_16} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/Resizer/UROM/UROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==UROM || ORIG_REF_NAME==UROM} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/RAM_81bit_32/RAM_81bit_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_81bit_32 || ORIG_REF_NAME==RAM_81bit_32} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/multi_0point2/multi_0point2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_0point2 || ORIG_REF_NAME==multi_0point2} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/ROM_32bit_11952_1/ROM_32bit_11952.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_32bit_11952 || ORIG_REF_NAME==ROM_32bit_11952} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/Resizer/VROM/VROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VROM || ORIG_REF_NAME==VROM} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/DDR/ip/MMCM/MMCM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MMCM || ORIG_REF_NAME==MMCM} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/RAM_16bit_16_1/RAM_16bit_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_16bit_16 || ORIG_REF_NAME==RAM_16bit_16} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/adder_32bit/adder_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_32bit || ORIG_REF_NAME==adder_32bit} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/RAM_16bit_1225_1/RAM_16bit_1225.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_16bit_1225 || ORIG_REF_NAME==RAM_16bit_1225} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/ROM_16bit_1368_1/ROM_16bit_1368.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_16bit_1368 || ORIG_REF_NAME==ROM_16bit_1368} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Top/IP/PLL/PLL.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/Resizer/ROM_8bit_260/ROM_8bit_260.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_8bit_260 || ORIG_REF_NAME==ROM_8bit_260} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/DDR/ip/FIFO/FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO || ORIG_REF_NAME==FIFO} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/adder_16bit_1/adder_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adder_16bit || ORIG_REF_NAME==adder_16bit} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/subtracter_16bit/subtracter_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==subtracter_16bit || ORIG_REF_NAME==subtracter_16bit} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/exp_1/exp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp || ORIG_REF_NAME==exp} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/Resizer/mult_16_8_24/mult_16_8_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_16_8_24 || ORIG_REF_NAME==mult_16_8_24} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/RAM_15bit_32_1/RAM_15bit_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_15bit_32 || ORIG_REF_NAME==RAM_15bit_32} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/DDR/ip/AHB_to_AXI_1/AHB_to_AXI.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AHB_to_AXI || ORIG_REF_NAME==AHB_to_AXI} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/DDR/ip/MIG/MIG.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIG || ORIG_REF_NAME==MIG} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/Resizer/ROM_9bit_260/ROM_9bit_260.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_9bit_260 || ORIG_REF_NAME==ROM_9bit_260} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/multi_16bit_p1_1/multi_16bit_p1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_16bit_p1 || ORIG_REF_NAME==multi_16bit_p1} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/RAM_14bit_32_1/RAM_14bit_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_14bit_32 || ORIG_REF_NAME==RAM_14bit_32} -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl_no_l2/Peripherals/ACC/IP/multi_16bit_1/multi_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multi_16bit || ORIG_REF_NAME==multi_16bit} -quiet] -quiet
