# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/RAM_16bit_1225_1/RAM_16bit_1225.xci
# IP: The module: 'RAM_16bit_1225' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/RAM_16bit_1225_1/RAM_16bit_1225_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_16bit_1225'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/RAM_16bit_1225_1/RAM_16bit_1225.xci
# IP: The module: 'RAM_16bit_1225' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/SoC/Projects/CortexM3_soc/Rtl/Peripherals/ACC/IP/RAM_16bit_1225_1/RAM_16bit_1225_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_16bit_1225'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
