##Clock
set_property IOSTANDARD LVCMOS33 [get_ports CLK50M]
set_property PACKAGE_PIN K18 [get_ports CLK50M]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CAMERA_PCLK_IBUF]

##Reset
set_property IOSTANDARD LVCMOS33 [get_ports RSTn]
set_property IOSTANDARD LVCMOS33 [get_ports RST_LED]
set_property PACKAGE_PIN B16 [get_ports RSTn]
set_property PACKAGE_PIN P19 [get_ports RST_LED]


##SWD
set_property IOSTANDARD LVCMOS33 [get_ports SWDIO]
set_property IOSTANDARD LVCMOS33 [get_ports SWCLK]
set_property PACKAGE_PIN W19 [get_ports SWDIO]
set_property PACKAGE_PIN V20 [get_ports SWCLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SWCLK]

##UART
set_property IOSTANDARD LVCMOS33 [get_ports RXD]
set_property IOSTANDARD LVCMOS33 [get_ports TXD]
set_property IOSTANDARD LVCMOS33 [get_ports TXDLED]
set_property PACKAGE_PIN AB22 [get_ports RXD]
set_property PACKAGE_PIN AB21 [get_ports TXD]
set_property PACKAGE_PIN AA21 [get_ports TXDLED]


##DDR
set_property IOSTANDARD LVCMOS33 [get_ports init_calib_complete]
set_property PACKAGE_PIN P20 [get_ports init_calib_complete]


##KEY
set_property IOSTANDARD LVCMOS33 [get_ports row]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property PACKAGE_PIN AA9 [get_ports row]
set_property PACKAGE_PIN T14 [get_ports {col[0]}]
set_property PACKAGE_PIN AA11 [get_ports {col[1]}]
set_property PACKAGE_PIN W11 [get_ports {col[2]}]
set_property PACKAGE_PIN AB10 [get_ports {col[3]}]


##DIGTAL TUBE
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property PACKAGE_PIN AA16 [get_ports {seg[0]}]
set_property PACKAGE_PIN AB15 [get_ports {seg[1]}]
set_property PACKAGE_PIN AB16 [get_ports {seg[2]}]
set_property PACKAGE_PIN AB17 [get_ports {seg[3]}]
set_property PACKAGE_PIN W14 [get_ports {seg[4]}]
set_property PACKAGE_PIN Y17 [get_ports {seg[5]}]
set_property PACKAGE_PIN AA15 [get_ports {seg[6]}]
set_property PACKAGE_PIN Y16 [get_ports {seg[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dig[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dig[0]}]
set_property PACKAGE_PIN AA14 [get_ports {dig[5]}]
set_property PACKAGE_PIN AB11 [get_ports {dig[4]}]
set_property PACKAGE_PIN Y13 [get_ports {dig[3]}]
set_property PACKAGE_PIN AA13 [get_ports {dig[2]}]
set_property PACKAGE_PIN AB13 [get_ports {dig[1]}]
set_property PACKAGE_PIN Y14 [get_ports {dig[0]}]


##LCD
set_property IOSTANDARD LVCMOS33 [get_ports LCD_CS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_WR]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RD]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RST]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_BL_CTR]
set_property PACKAGE_PIN J21 [get_ports LCD_CS]
set_property PACKAGE_PIN J20 [get_ports LCD_RS]
set_property PACKAGE_PIN M16 [get_ports LCD_WR]
set_property PACKAGE_PIN M15 [get_ports LCD_RD]
set_property PACKAGE_PIN L13 [get_ports LCD_RST]
set_property PACKAGE_PIN K19 [get_ports LCD_BL_CTR]

set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[15]}]
set_property PACKAGE_PIN M13 [get_ports {LCD_DATA[0]}]
set_property PACKAGE_PIN L15 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN L14 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN K14 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN K13 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN K16 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN L16 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN L18 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN M18 [get_ports {LCD_DATA[8]}]
set_property PACKAGE_PIN J17 [get_ports {LCD_DATA[9]}]
set_property PACKAGE_PIN K17 [get_ports {LCD_DATA[10]}]
set_property PACKAGE_PIN H18 [get_ports {LCD_DATA[11]}]
set_property PACKAGE_PIN H17 [get_ports {LCD_DATA[12]}]
set_property PACKAGE_PIN H19 [get_ports {LCD_DATA[13]}]
set_property PACKAGE_PIN J19 [get_ports {LCD_DATA[14]}]
set_property PACKAGE_PIN M17 [get_ports {LCD_DATA[15]}]


##CAMERA

set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_PCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_PWDN]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_HREF]
set_property IOSTANDARD LVCMOS33 [get_ports CAMERA_RST]
set_property PACKAGE_PIN N13 [get_ports CAMERA_SCL]
set_property PACKAGE_PIN P15 [get_ports CAMERA_SDA]
set_property PACKAGE_PIN N20 [get_ports CAMERA_PCLK]
set_property PACKAGE_PIN N22 [get_ports CAMERA_PWDN]
set_property PACKAGE_PIN N14 [get_ports CAMERA_VSYNC]
set_property PACKAGE_PIN R16 [get_ports CAMERA_HREF]
set_property PACKAGE_PIN T18 [get_ports CAMERA_RST]

set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAMERA_DATA[7]}]
set_property PACKAGE_PIN R18 [get_ports {CAMERA_DATA[0]}]
set_property PACKAGE_PIN P17 [get_ports {CAMERA_DATA[1]}]
set_property PACKAGE_PIN N17 [get_ports {CAMERA_DATA[2]}]
set_property PACKAGE_PIN N19 [get_ports {CAMERA_DATA[3]}]
set_property PACKAGE_PIN N18 [get_ports {CAMERA_DATA[4]}]
set_property PACKAGE_PIN L20 [get_ports {CAMERA_DATA[5]}]
set_property PACKAGE_PIN L19 [get_ports {CAMERA_DATA[6]}]
set_property PACKAGE_PIN M20 [get_ports {CAMERA_DATA[7]}]


##GPIO
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN M21 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN H13 [get_ports {GPIO[1]}]
set_property PACKAGE_PIN K21 [get_ports {GPIO[2]}]
set_property PACKAGE_PIN J14 [get_ports {GPIO[3]}]
set_property PACKAGE_PIN J15 [get_ports {GPIO[4]}]
set_property PACKAGE_PIN G15 [get_ports {GPIO[5]}]
set_property PACKAGE_PIN G17 [get_ports {GPIO[6]}]
set_property PACKAGE_PIN J22 [get_ports {GPIO[7]}]
set_property PACKAGE_PIN R19 [get_ports {GPIO[8]}]
set_property PACKAGE_PIN T20 [get_ports {GPIO[9]}]
set_property PACKAGE_PIN T21 [get_ports {GPIO[10]}]
set_property PACKAGE_PIN U21 [get_ports {GPIO[11]}]
set_property PACKAGE_PIN U22 [get_ports {GPIO[12]}]
set_property PACKAGE_PIN W22 [get_ports {GPIO[13]}]
set_property PACKAGE_PIN W21 [get_ports {GPIO[14]}]
set_property PACKAGE_PIN V22 [get_ports {GPIO[15]}]
set_property DRIVE 16 [get_ports {GPIO[15]}]
set_property DRIVE 16 [get_ports {GPIO[14]}]
set_property DRIVE 16 [get_ports {GPIO[13]}]
set_property DRIVE 16 [get_ports {GPIO[12]}]
set_property DRIVE 16 [get_ports {GPIO[11]}]
set_property DRIVE 16 [get_ports {GPIO[10]}]
set_property DRIVE 16 [get_ports {GPIO[9]}]
set_property DRIVE 16 [get_ports {GPIO[8]}]
set_property DRIVE 16 [get_ports {GPIO[7]}]
set_property DRIVE 16 [get_ports {GPIO[6]}]
set_property DRIVE 16 [get_ports {GPIO[5]}]
set_property DRIVE 16 [get_ports {GPIO[4]}]
set_property DRIVE 16 [get_ports {GPIO[3]}]
set_property DRIVE 16 [get_ports {GPIO[2]}]
set_property DRIVE 16 [get_ports {GPIO[1]}]
set_property DRIVE 16 [get_ports {GPIO[0]}]

create_clock -period 20.000 -name clk_global -waveform {0.000 10.000} -add [get_ports CLK50M]
create_clock -period 41.667 -name camera_clk -waveform {0.000 20.834} -add [get_ports CAMERA_PCLK]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list pclk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {CAMERA_DATA_IBUF[0]} {CAMERA_DATA_IBUF[1]} {CAMERA_DATA_IBUF[2]} {CAMERA_DATA_IBUF[3]} {CAMERA_DATA_IBUF[4]} {CAMERA_DATA_IBUF[5]} {CAMERA_DATA_IBUF[6]} {CAMERA_DATA_IBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list CAMERA_HREF_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list CAMERA_VSYNC_IBUF]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list SynClock.Global_CLK_PLL/inst/clk_50M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 2 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {CAMEARA/state[0]} {CAMEARA/state[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list CAMERA_PWDN_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list CAMERA_RST_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list CAMERA_SCL_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list CAMEARA/DATA_VALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list AHB_to_CAMERA/sdai]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list AHB_to_CAMERA/sdao]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
